parameters:

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: bryce

  flavor_name:
    type: string
    description: Instance type for web and DB servers
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type

  image_name:
    type: string
    description: >
    default: Centos-Latest
